apiVersion: v1
kind: Service
metadata:
  namespace: $NAMESPACE
  name: $SERVICE
spec:
  ports:
    - port: $RUNPORT_POSTGRE
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $NAMESPACE
  name: postgres
spec:
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 0   # Never take a pod down until a new one is ready
  #     maxSurge: 1         # Add at most one extra pod during update
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: $HUB/$REPOSITORY:$TAG
          env:
            - name: POSTGRES_DB
              value: $POSTGRES_DB
            - name: POSTGRES_USER
              value: $POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: $POSTGRES_PASSWORD
          ports:
            - containerPort: $RUNPORT_POSTGRE
          # readinessProbe:
          #   exec:
          #     command:
          #       - pg_isready
          #       - -U
          #       - catalog
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
