apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: product-catalog-backend:latest
          env:
            - name: POSTGRES_DB
              value: catalog
            - name: POSTGRES_USER
              value: catalog
            - name: POSTGRES_PASSWORD
              value: catalog
          ports:
            - containerPort: 5432
