FROM node:22-bullseye

# Install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --no-cache-dir openai

# Optional: verify installation
RUN python3 --version && pip3 --version

# Set working directory
WORKDIR /app

# Install Node.js dependencies
COPY algorithmic-hue/data-access/package*.json ./
RUN npm ci

# Copy app files
COPY algorithmic-hue/data-access/ .

# Expose port
ARG EXPOSE_PORT
EXPOSE $EXPOSE_PORT

# Start server
CMD ["node", "server.js"]