apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
    - port: 80
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: product-catalog-frontend:latest
          ports:
            - containerPort: 80
