FROM node:20-alpine AS build
WORKDIR /app
COPY product-catalog-frontend/package*.json ./
RUN npm ci
COPY product-catalog-frontend/ ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

# WHEN RUNNING FROM A WEB SERVER, THIS VERSION RESPECTS .ENV NODE_ENV PROPERTY
# FOR EXAMPLE, NODE_ENV=production VS NODE_ENV=development
